version: "3"

services:
  install-next:
    image: node:19.0.0-alpine
    working_dir: /home/node
    volumes:
      - "./web-app:/home/node"
    command: npm install

  next:
    depends_on:
      install-next:
        condition: service_completed_successfully
    image: node:19.0.0-alpine
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_KEY}
      NEXT_PUBLIC_CLIENT_API: "http://localhost:3001"
      NODE_ENV: development
    ports:
      - "3000:3000"
    user: node
    working_dir: /home/node
    volumes:
      - "./web-app:/home/node"
    command: sh -c "npm run dev"

  mongo:
    image: mongo:5.0.17
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/volumes:/data/db"

  api-gateway:
    image: node:19.0.0-alpine
    ports:
      - '3001:3001'
    user: node
    working_dir: /home/node
    environment:
      CORS: http://localhost:3000
      CATEGORY_SERVICE_HOST: category
      AUTH_SERVICE_HOST: auth
      ANNOUNCEMENT_SERVICE_HOST: announcement
      EVENT_SERVICE_HOST: event
      MESSAGE_SERVICE_HOST: message
      COMPANY_SERVICE_HOST: company
      USER_SERVICE_HOST: user
      PARTY_SERVICE_HOST: party
      VISIO_SERVICE_HOST: visio
    volumes:
      - "./nest-app/api-gateway:/home/node"
    command: sh -c "npm install && npm run start:dev"

  auth:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
    ports:
      - '4000:4000'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/auth:/home/node"
    command: sh -c "npm install && npm run start:dev"
  
  category:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
    ports:
      - '4001:4001'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/category:/home/node"
    command: sh -c "npm install && npm run start:dev"

  announcement:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    ports:
      - '4002:4002'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/announcement:/home/node"
    command: sh -c "npm install && npm run start:dev"

  party:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
    ports:
      - '4005:4005'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/party:/home/node"
    command: sh -c "npm install && npm run start:dev"
  
  event:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
    ports:
      - '4007:4007'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/event:/home/node"
    command: sh -c "npm install && npm run start:dev"

  message:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
    ports:
      - '4010:4010'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/message:/home/node"
    command: sh -c "npm install && npm run start:dev"

  company:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
      FRONT_URL: ${FRONT_URL}
    ports:
      - '4009:4009'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/company:/home/node"
    command: sh -c "npm install && npm run start:dev"

  user:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
      FRONT_URL: ${FRONT_URL}
    ports:
      - '4020:4020'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/user:/home/node"
    command: sh -c "npm install && npm run start:dev"

  visio:
    image: node:19.0.0-alpine
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY_SERVICE}
    ports:
      - '4015:4015'
    user: node
    working_dir: /home/node
    volumes:
      - "./nest-app/visio:/home/node"
    command: sh -c "npm install && npm run start:dev"